CI: embedings
manticoresoftware/columnar pull request #74
Opened 2024-12-11 10:04 UTC by donhardman

2024-12-11 10:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/manticoresoftware/columnar?pullRequest=74) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/manticoresoftware/columnar?pullRequest=74) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: glookka<br/>:x: donhardman<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/manticoresoftware/columnar?pullRequest=74) it.</sub>

2024-12-25 06:39 UTC, sanikolaev requested changes

2024-12-25 06:39 UTC, sanikolaev commented on .github/workflows/embedding_build_template.yml
> +          name: build_${{ inputs.distr }}_${{ inputs.arch }}
I suggest we rename the embedding artifact names to distinguish them from the other artifacts not related with embeddings.

2025-06-21 06:36 UTC, donhardman commented
Closing as all was merged already in different pull

2025-06-21 06:36 UTC, closed without merging